name: Release Action

on:
  release:
    types: [published]

jobs:
  publish-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/josedpiambav/feature
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create Action Version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get tag version
          VERSION=${GITHUB_REF#refs/tags/}

          # Validate semantic format
          if [[ ! $VERSION =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "::error::Versión inválida: $VERSION"
            exit 1
          fi

          # Create action file
          cat <<EOF > action.yml
          name: 'Feature Branching'
          description: 'Automatic PR merging with feature branching'
          inputs:
            trunk-branch:
              description: 'Base branch name'
              required: true
            labels:
              description: 'Comma-separated required labels'
              required: true
          runs:
            using: composite
            steps:
              - name: Merge PRs
                uses: docker://ghcr.io/josedpiambav/feature:$VERSION
          EOF
          
          # Configurar GitHub CLI
          sudo apt-get update && sudo apt-get install -y gh
          gh auth login --with-token <<< "$GH_TOKEN"

          git push -u origin release-$VERSION || {
            echo "::error::Push failed";
            exit 1;
          }

          PR_URL=$(gh pr create ... --json url -q .url) || {
            echo "::error::PR creation failed";
            exit 1;
          }

          sleep 60  # Ajustar según duración de los workflows
          gh pr merge $PR_URL --auto --squash --delete-branch || {
            echo "::warning::Auto-merge failed";
            gh pr comment $PR_URL --body "Merge automático falló. Requiere intervención manual.";
            exit 0;
          }